### ISSUE TITLE
我无法运行你的代码，缺少'data/data_add.csv'

### ISSUE THREAD

**Issue by wudgsfd** [HuiNinging/IPMpaper#1]
**这是我的控制台报错：**
Traceback (most recent call last):
  File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 267, in <module>
    data=pd.read_csv('data/data_add.csv',encoding='gb18030')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/data_add.csv'

**Comment by HuiNinging** [comment]
你好：


这个论文的完整数据是学生数据，出于隐私保护并未公开全部数据，代码中提供的是示例数据，使用全部数据训练好的模型代码中已经提供了。这个data_add.csv你可以认为和提供的示例数据data_part.csv的数据一样，只是数据量较多。如果出于练习的目的重新训练模型可以考虑使用已有的数据增强数据集。




惠柠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1)





 
这是我的控制台报错：
 Traceback (most recent call last):
 File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 267, in 
 data=pd.read_csv('data/data_add.csv',encoding='gb18030')
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
 return _read(filepath_or_buffer, kwds)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
 parser = TextFileReader(filepath_or_buffer, **kwds)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in init
 self._engine = self._make_engine(f, self.engine)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
 self.handles = get_handle(
 ^^^^^^^^^^^
 File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
 handle = open(
 ^^^^^
 FileNotFoundError: [Errno 2] No such file or directory: 'data/data_add.csv'

**Comment by wudgsfd** [comment]
那请问应该怎么修改呢，把data_add.csv换成datapart.csv也不行啊。
Traceback (most recent call last):
&nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3790, in get_loc
&nbsp; &nbsp; return self._engine.get_loc(casted_key)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
&nbsp; File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
&nbsp; File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
&nbsp; File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'comment'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
&nbsp; File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 268, in <module&gt;
&nbsp; &nbsp; result_comments = pretreatment(list(data['comment'].values))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ~~~~^^^^^^^^^^^
&nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 3893, in __getitem__
&nbsp; &nbsp; indexer = self.columns.get_loc(key)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3797, in get_loc
&nbsp; &nbsp; raise KeyError(key) from err
KeyError: 'comment'





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1)





 你好： 
 
 
 这个论文的完整数据是学生数据，出于隐私保护并未公开全部数据，代码中提供的是示例数据，使用全部数据训练好的模型代码中已经提供了。这个data_add.csv你可以认为和提供的示例数据data_part.csv的数据一样，只是数据量较多。如果出于练习的目的重新训练模型可以考虑使用已有的数据增强数据集。 
 
 
 
 
 惠柠 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月14日(星期二) 上午10:37 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1) 
 
 
 
 
 
   
 这是我的控制台报错： 
  Traceback (most recent call last): 
  File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 267, in  
  data=pd.read_csv('data/data_add.csv',encoding='gb18030') 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv 
  return _read(filepath_or_buffer, kwds) 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read 
  parser = TextFileReader(filepath_or_buffer, **kwds) 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in init 
  self._engine = self._make_engine(f, self.engine) 
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine 
  self.handles = get_handle( 
  ^^^^^^^^^^^ 
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 863, in get_handle 
  handle = open( 
  ^^^^^ 
  FileNotFoundError: [Errno 2] No such file or directory: 'data/data_add.csv'

**Comment by HuiNinging** [comment]
你好：


如果你要重新训练模型就注释掉test_model那行代码，使用train_model那行代码再更改数据读取路径。此外，这个代码已经是一年以前写的了，如果你只是练习模型可以考虑参考该模型的其他作者代码。




惠柠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1)





 那请问应该怎么修改呢，把data_add.csv换成datapart.csv也不行啊。 
 Traceback (most recent call last): 
 &amp;nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3790, in get_loc 
 &amp;nbsp; &amp;nbsp; return self._engine.get_loc(casted_key) 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 &amp;nbsp; File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc 
 &amp;nbsp; File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc 
 &amp;nbsp; File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item 
 &amp;nbsp; File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item 
 KeyError: 'comment' 
 
 
 The above exception was the direct cause of the following exception: 
 
 
 Traceback (most recent call last): 
 &amp;nbsp; File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 268, in <module&amp;gt; 
 &amp;nbsp; &amp;nbsp; result_comments = pretreatment(list(data['comment'].values)) 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ~~~~^^^^^^^^^^^ 
 &amp;nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 3893, in __getitem__ 
 &amp;nbsp; &amp;nbsp; indexer = self.columns.get_loc(key) 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^ 
 &amp;nbsp; File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3797, in get_loc 
 &amp;nbsp; &amp;nbsp; raise KeyError(key) from err 
 KeyError: 'comment' 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年11月14日(星期二) 上午10:50 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1) 
 
 
 
 
 
  你好：  
   
   
  这个论文的完整数据是学生数据，出于隐私保护并未公开全部数据，代码中提供的是示例数据，使用全部数据训练好的模型代码中已经提供了。这个data_add.csv你可以认为和提供的示例数据data_part.csv的数据一样，只是数据量较多。如果出于练习的目的重新训练模型可以考虑使用已有的数据增强数据集。  
   
   
   
   
  惠柠  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "HuiNinging/IPMpaper"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年11月14日(星期二) 上午10:37  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[HuiNinging/IPMpaper] 我无法运行你的代码，缺少'data/data_add.csv' (Issue #1)  
   
   
   
   
   
     
  这是我的控制台报错：  
   Traceback (most recent call last):  
   File "C:\Users\A\Desktop\IPMpaper-main\bert_bilstm_att.py", line 267, in   
   data=pd.read_csv('data/data_add.csv',encoding='gb18030')  
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
   File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv  
   return _read(filepath_or_buffer, kwds)  
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
   File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read  
   parser = TextFileReader(filepath_or_buffer, **kwds)  
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
   File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in init  
   self._engine = self._make_engine(f, self.engine)  
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
   File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine  
   self.handles = get_handle(  
   ^^^^^^^^^^^  
   File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 863, in get_handle  
   handle = open(  
   ^^^^^  
   FileNotFoundError: [Errno 2] No such file or directory: 'data/data_add.csv'
